replicaCount: 1

service:
  type: ClusterIP
  port: 5000
  selector:
    app.kubernetes.io/name: llama-stack
 
image:
  repository: docker.io/llamastack/distribution-remote-vllm
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

volumes:
  - name: llama-storage
    persistentVolumeClaim:
      claimName: llama-pvc
  - name: llama-stack-config
    configMap:
      name: config.yaml

volumeMounts:
  - name: llama-storage
    mountPath: /root/.llama
  - name: llama-stack-config
    mountPath: /app/config.yaml
